services:
  postgres:
    image: postgres:15
    container_name: bigs_postgres
    environment:
      POSTGRES_DB: bigs
      POSTGRES_USER: bigs
      POSTGRES_PASSWORD: bigs_password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bigs"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
